In [8]:
from keras.datasets import mnist
import matplotlib.pyplot as plt

# Setup train and test splits
(x_train, y_train), (x_test, y_test) = mnist.load_data()

print("Training data shape: ", x_train.shape)  
print("Test data shape", x_test.shape)  

# Flatten the images
image_vector_size = 28*28

x_train = x_train.reshape(60000,784)
x_test = x_test.reshape(10000,784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print("Train Samples: ", x_train.shape)  
print("Test Samples", x_test.shape)  

Training data shape:  (60000, 28, 28)
Test data shape (10000, 28, 28)
Train Samples:  (60000, 784)
Test Samples (10000, 784)


In [9]:
import keras
from keras.datasets import mnist

# Setup train and test splits
# (x_train, y_train), (x_test, y_test) = mnist.load_data()
print("Training label shape: ", y_train.shape)  
print("First 5 training labels: ", y_train[:5])  

num_classes = 10
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
print("First 5 training lables as one-hot encoded vectors:\n", y_train[:5])
print("Shape after encoding: ", y_train.shape)

Training label shape:  (60000,)
First 5 training labels:  [5 0 4 1 9]
First 5 training lables as one-hot encoded vectors:
 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Shape after encoding:  (60000, 10)


In [10]:
from keras.layers import Dense  
from keras.models import Sequential

image_size = 28*28  
num_classes = 10

model = Sequential()
model.add(Dense(units=8, activation='sigmoid', input_shape=(784,)))
model.add(Dense(units=num_classes, activation='softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 8)                 6280      
_________________________________________________________________
dense_4 (Dense)              (None, 10)                90        
Total params: 6,370
Trainable params: 6,370
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(optimizer="sgd", loss='categorical_crossentropy', metrics=['accuracy'])

In [12]:
history = model.fit(x_train, y_train, batch_size=128, epochs=5, verbose=1, validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 3s 46us/step - loss: 2.2229 - accuracy: 0.1868 - val_loss: 2.1185 - val_accuracy: 0.3602
Epoch 2/5
60000/60000 [==============================] - 2s 31us/step - loss: 2.0345 - accuracy: 0.4622 - val_loss: 1.9469 - val_accuracy: 0.5701
Epoch 3/5
60000/60000 [==============================] - 2s 32us/step - loss: 1.8673 - accuracy: 0.6220 - val_loss: 1.7812 - val_accuracy: 0.6707
Epoch 4/5
60000/60000 [==============================] - 2s 31us/step - loss: 1.7069 - accuracy: 0.6961 - val_loss: 1.6247 - val_accuracy: 0.7133
Epoch 5/5
60000/60000 [==============================] - 2s 30us/step - loss: 1.5585 - accuracy: 0.7294 - val_loss: 1.4826 - val_accuracy: 0.7451


In [13]:
score = model.evaluate(x_test, y_test, verbose=1)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

10000/10000 [==============================] - 1s 55us/step
Test loss: 1.482565480041504
Test accuracy: 0.7451000213623047
